name: LSDelivery
authors: [Bremado,sh4wsz]
version: 1.0
main: studio.lothus.delivery.LothusDelivery
description: A plugin that allows you to deliver items to players.
commands:
  delivery:
  create:
  hologram: